kind: pipeline
name: default

steps:
- name: build
  image: alpine/helm
  commands:
  - env
  - apk update
  - apk add coreutils
  - cd helm
  - ./template.sh

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: '*'
  when:
    event: tag

---
kind: secret
name: github_token
get:
  path: secret/drone/github
  name: token