version: '2'

services:
  nginx:
    image: keymetrics/km-nginx:dedicated
    restart: always
    ports:
      - "80:80"
    links:
      - km-wizard
      - km-api
      - km-front
      
  elasticsearch:
    image: elasticsearch:5.5
    restart: always
    volumes:
      - "esdata:/usr/share/elasticsearch/data"

  mongodb:
    image: mongo:3.4
    restart: always
    volumes:
      - "mongodata:/data/db"
      
  redis:
    image: redis:3.0
    restart: always

  km-wizard:
    image: keymetrics/km-wizard-dedicated
    restart: always
    links:
      - redis
      - mongodb
    environment:
      KM_MONGO_URL: mongodb://mongodb:27017/keymetrics
      KM_REDIS_URL: redis://redis:6379
      
  km-api:
    image: keymetrics/km-api-dedicated:latest
    restart: always
    ports:
      - 3900:3900
      - 43554:43554
    links:
      - redis
      - elasticsearch
      - mongodb
    environment:
      KM_ELASTICSEARCH_HOST: elasticsearch:9200
      KM_ELASTIC_VERSION: '5.5'
      KM_MONGO_URL: mongodb://mongodb:27017/keymetrics
      KM_REDIS_URL: redis://redis:6379
      NODE_ENV: "dedicated"
      PM2_MACHINE_NAME: km-keymetrics
      
  km-front:
    image: keymetrics/noex-enterprise:latest
    restart: always
    
volumes:
  esdata:
  mongodata:
